import type { Metadata } from "next";
import { Inter, Tajawal } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/useAppContext";
import { cn } from "@/lib/utils";
import { Analytics } from "@vercel/analytics/react";

// const font = Inter({ subsets: ["latin"], variable: "--font-sans" });

const font = Tajawal({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900", "800"], // Select specific weights
});

export const metadata: Metadata = {
  title: "FurniSty ECOM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "relative h-full")}>
        <AppContextProvider>{children}</AppContextProvider>
        <Analytics />
      </body>
    </html>
  );
}
